//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;



/// <summary>
///   A strongly-typed resource class, for looking up localized strings, etc.
/// </summary>
// This class was auto-generated by the StronglyTypedResourceBuilder
// class via a tool like ResGen or Visual Studio.
// To add or remove a member, edit your .ResX file then rerun ResGen
// with the /str option, or rebuild your VS project.
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
internal class MySqlResources {
    
    private static global::System.Resources.ResourceManager resourceMan;
    
    private static global::System.Globalization.CultureInfo resourceCulture;
    
    [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
    internal MySqlResources() {
    }
    
    /// <summary>
    ///   Returns the cached ResourceManager instance used by this class.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Resources.ResourceManager ResourceManager {
        get {
            if (object.ReferenceEquals(resourceMan, null)) {
                global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MySqlResources", typeof(MySqlResources).Assembly);
                resourceMan = temp;
            }
            return resourceMan;
        }
    }
    
    /// <summary>
    ///   Overrides the current thread's CurrentUICulture property for all
    ///   resource lookups using this strongly typed resource class.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Globalization.CultureInfo Culture {
        get {
            return resourceCulture;
        }
        set {
            resourceCulture = value;
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to select COLUMN_NAME, ORDINAL_POSITION, DATA_TYPE, CHARACTER_MAXIMUM_LENGTH, IS_NULLABLE, COLUMN_KEY
    ///from INFORMATION_SCHEMA.COLUMNS
    ///where TABLE_SCHEMA=@schema AND TABLE_NAME=@table.
    /// </summary>
    internal static string InformationQueryStatement {
        get {
            return ResourceManager.GetString("InformationQueryStatement", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to select t_span.*
    ///from (
    ///	select t_sorted.*
    ///	from (
    ///		select $(column-list)
    ///		from $(schema).$(table)
    ///		order by $(watermark-column)
    ///	) t_sorted	
    ///	limit @limit offset @offset	
    ///) t_span.
    /// </summary>
    internal static string OffsetQueryStatement {
        get {
            return ResourceManager.GetString("OffsetQueryStatement", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to select t_span.*
    ///from (
    ///	select t_sorted.*
    ///	from (
    ///		select $(column)
    ///		from $(schema).$(table)
    ///		order by $(column)
    ///	) t_sorted
    ///	offset @offset
    ///) t_span
    ///limit 1.
    /// </summary>
    internal static string WatermarkValueQueryStatement {
        get {
            return ResourceManager.GetString("WatermarkValueQueryStatement", resourceCulture);
        }
    }
}
