//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;



/// <summary>
///   A strongly-typed resource class, for looking up localized strings, etc.
/// </summary>
// This class was auto-generated by the StronglyTypedResourceBuilder
// class via a tool like ResGen or Visual Studio.
// To add or remove a member, edit your .ResX file then rerun ResGen
// with the /str option, or rebuild your VS project.
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
internal class Resources {
    
    private static global::System.Resources.ResourceManager resourceMan;
    
    private static global::System.Globalization.CultureInfo resourceCulture;
    
    [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
    internal Resources() {
    }
    
    /// <summary>
    ///   Returns the cached ResourceManager instance used by this class.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Resources.ResourceManager ResourceManager {
        get {
            if (object.ReferenceEquals(resourceMan, null)) {
                global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources", typeof(Resources).Assembly);
                resourceMan = temp;
            }
            return resourceMan;
        }
    }
    
    /// <summary>
    ///   Overrides the current thread's CurrentUICulture property for all
    ///   resource lookups using this strongly typed resource class.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Globalization.CultureInfo Culture {
        get {
            return resourceCulture;
        }
        set {
            resourceCulture = value;
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to create table if not exists engine_version(
    ///	Id text not null
    ///);
    ///create table if not exists job_parameters(
    ///	Id text not null primary key,
    ///	Hash text not null,
    ///	Parameters text not null
    ///);
    ///create table if not exists cache_files(
    ///	Id text not null primary key,
    ///	QueryHash text not null,
    ///	SubsetId integer not null,
    ///	FilePath text not null,
    ///	FileType text not null,
    ///	CompressionType int not null,
    ///	QueryCount int not null,
    ///	ActualCount int not null,
    ///	CommitOffset int not null,
    ///	MergeOffset int no [rest of string was truncated]&quot;;.
    /// </summary>
    internal static string CreateRestorePointSchemaStatement {
        get {
            return ResourceManager.GetString("CreateRestorePointSchemaStatement", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to delete from cache_files where Id=@Id.
    /// </summary>
    internal static string DeleteCacheFileDescriptorStatement {
        get {
            return ResourceManager.GetString("DeleteCacheFileDescriptorStatement", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to delete from telemetry_counters;
    ///delete from telemetry_numerics;
    ///delete from telemetry_kvs;.
    /// </summary>
    internal static string DeleteTelemetryStatement {
        get {
            return ResourceManager.GetString("DeleteTelemetryStatement", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to insert into cache_files(Id,QueryHash,SubsetId,FilePath,FileType,CompressionType,QueryCount,ActualCount,CommitOffset,MergeOffset,ContentHash,SizeInBytes)
    ///values (@Id,@QueryHash,@SubsetId,@FilePath,@FileType,@CompressionType,@QueryCount,@ActualCount,@CommitOffset,@MergeOffset,@ContentHash,@SizeInBytes);.
    /// </summary>
    internal static string InsertCacheFileDescriptorStatement {
        get {
            return ResourceManager.GetString("InsertCacheFileDescriptorStatement", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to insert or ignore into job_parameters(Id,Hash,Parameters) 
    ///values(&apos;9e905e95-cbab-4c4f-b26a-241ea554812f&apos;,@Hash,@Parameters);.
    /// </summary>
    internal static string InsertJobParametersStatement {
        get {
            return ResourceManager.GetString("InsertJobParametersStatement", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to insert into telemetry_counters (Key, Value)
    ///values (@Key, @Value);.
    /// </summary>
    internal static string InsertTelemetryCounterStatement {
        get {
            return ResourceManager.GetString("InsertTelemetryCounterStatement", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to insert into telemetry_kvs (Key,Type,Value)
    ///values (@Key,@Type,@Value);.
    /// </summary>
    internal static string InsertTelemetryKeyValueStatement {
        get {
            return ResourceManager.GetString("InsertTelemetryKeyValueStatement", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to insert into telemetry_numerics (Key,Min,Max,MeanCount,MeanTotal,Value)
    ///values (@Key,@Min,@Max,@MeanCount,@MeanTotal,@Value);.
    /// </summary>
    internal static string InsertTelemetryNumericStatement {
        get {
            return ResourceManager.GetString("InsertTelemetryNumericStatement", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to select *
    ///from cache_files
    ///where QueryHash=@queryHash;.
    /// </summary>
    internal static string SelectCacheFileDescriptorStatement {
        get {
            return ResourceManager.GetString("SelectCacheFileDescriptorStatement", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to select Hash,Parameters
    ///from job_parameters
    ///where id=&apos;9e905e95-cbab-4c4f-b26a-241ea554812f&apos;;.
    /// </summary>
    internal static string SelectJobParametersStatement {
        get {
            return ResourceManager.GetString("SelectJobParametersStatement", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to select CommittedOffset from job_snapshot
    ///where Id=&apos;9e905e95-cbab-4c4f-b26a-241ea554812f&apos;;.
    /// </summary>
    internal static string SelectJobSnapshotStatement {
        get {
            return ResourceManager.GetString("SelectJobSnapshotStatement", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to select * from telemetry_counters;
    ///select * from telemetry_numerics;
    ///select * from telemetry_kvs;.
    /// </summary>
    internal static string SelectTelemetryStatement {
        get {
            return ResourceManager.GetString("SelectTelemetryStatement", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to insert or replace into job_snapshot
    ///values (&apos;9e905e95-cbab-4c4f-b26a-241ea554812f&apos;,@CommittedOffset);.
    /// </summary>
    internal static string UpsertJobSnapshotStatement {
        get {
            return ResourceManager.GetString("UpsertJobSnapshotStatement", resourceCulture);
        }
    }
}
